-- Update food_items.image_path for existing menu items.
-- Paths follow the local Windows asset location as requested.

UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Aloo Paratha.png' WHERE name = 'Aloo Paratha';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Alu Bhorta.png' WHERE name = 'Alu Bhorta';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\BBQ Chicken Pizza.png' WHERE name = 'BBQ Chicken Pizza';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Beef Chow Mein.png' WHERE name = 'Beef Chow Mein';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Beef Kala Bhuna.png' WHERE name = 'Beef Kala Bhuna';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Beef Seekh Kebab.png' WHERE name = 'Beef Seekh Kebab';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Beef Tehari.png' WHERE name = 'Beef Tehari';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Begun Bhorta.png' WHERE name = 'Begun Bhorta';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Bhuna Khichuri.png' WHERE name = 'Bhuna Khichuri';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Butter Chicken.png' WHERE name = 'Butter Chicken';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Butter Naan.png' WHERE name = 'Butter Naan';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chana Masala.png' WHERE name = 'Chana Masala';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Biriyani.png' WHERE name = 'Chicken Biriyani';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Biryani.png' WHERE name = 'Chicken Biryani';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Chow Mein.png' WHERE name = 'Chicken Chow Mein';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Curry.png' WHERE name = 'Chicken Curry';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Dumplings.png' WHERE name = 'Chicken Dumplings';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Fried Rice.png' WHERE name = 'Chicken Fried Rice';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Korma.png' WHERE name = 'Chicken Korma';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Manchurian.png' WHERE name = 'Chicken Manchurian';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Ramen.png' WHERE name = 'Chicken Ramen';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Rezala.png' WHERE name = 'Chicken Rezala';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Shawarma.png' WHERE name = 'Chicken Shawarma';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Tikka Masala.png' WHERE name = 'Chicken Tikka Masala';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Chicken Wonton Soup.png' WHERE name = 'Chicken Wonton Soup';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Classic Beef Burger.png' WHERE name = 'Classic Beef Burger';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Crispy Fries.png' WHERE name = 'Crispy Fries';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Dal Makhani.png' WHERE name = 'Dal Makhani';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Falafel Wrap.png' WHERE name = 'Falafel Wrap';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Fish Fry.png' WHERE name = 'Fish Fry';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Garlic Naan.png' WHERE name = 'Garlic Naan';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Hot and Sour Soup.png' WHERE name = 'Hot and Sour Soup';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Jeera Rice.png' WHERE name = 'Jeera Rice';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Kung Pao Chicken.png' WHERE name = 'Kung Pao Chicken';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Lentil Dal.png' WHERE name = 'Lentil Dal';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Margherita Pizza.png' WHERE name = 'Margherita Pizza';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Mixed Veg Curry.png' WHERE name = 'Mixed Veg Curry';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Mutton Kacchi.png' WHERE name = 'Mutton Kacchi';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Mutton Rogan Josh.png' WHERE name = 'Mutton Rogan Josh';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Palak Paneer.png' WHERE name = 'Palak Paneer';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Paneer Butter Masala.png' WHERE name = 'Paneer Butter Masala';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Paneer Tikka.png' WHERE name = 'Paneer Tikka';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Pepperoni Pizza.png' WHERE name = 'Pepperoni Pizza';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Plain Rice.png' WHERE name = 'Plain Rice';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Polao.png' WHERE name = 'Polao';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Raita.png' WHERE name = 'Raita';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Salmon Sushi Roll.png' WHERE name = 'Salmon Sushi Roll';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Seasonal Pitha.png' WHERE name = 'Seasonal Pitha';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Shorshe Ilish.png' WHERE name = 'Shorshe Ilish';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Spring Rolls.png' WHERE name = 'Spring Rolls';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Sweet and Sour Chicken.png' WHERE name = 'Sweet and Sour Chicken';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Szechuan Noodles.png' WHERE name = 'Szechuan Noodles';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Tandoori Chicken.png' WHERE name = 'Tandoori Chicken';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Biryani.png' WHERE name = 'Veg Biryani';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Chow Mein.png' WHERE name = 'Veg Chow Mein';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Dumplings.png' WHERE name = 'Veg Dumplings';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Hakka Noodles.png' WHERE name = 'Veg Hakka Noodles';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Manchurian.png' WHERE name = 'Veg Manchurian';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veg Supreme Pizza.png' WHERE name = 'Veg Supreme Pizza';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Vegetable Bhorta Platter.png' WHERE name = 'Vegetable Bhorta Platter';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Vegetable Fried Rice.png' WHERE name = 'Vegetable Fried Rice';
UPDATE food_items SET image_path = 'D:\FOODPANDA\frontend\src\assets\food\Veggie Pesto Pasta.png' WHERE name = 'Veggie Pesto Pasta';

COMMIT;
