SET DEFINE OFF;

-- One owner per restaurant.
-- Login password for all owners: 1234
-- Password hash generated by bcryptjs (cost 10).

-- Tasty Bites
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Tasty Bites Owner', NULL, 'tastybites@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'tastybites@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-TASTYBITES'
FROM users u
WHERE u.email = 'tastybites@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'tastybites@owner.com')
WHERE name = 'Tasty Bites';

-- Noodle House
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Noodle House Owner', NULL, 'noodlehouse@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'noodlehouse@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-NOODLEHOUSE'
FROM users u
WHERE u.email = 'noodlehouse@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'noodlehouse@owner.com')
WHERE name = 'Noodle House';

-- Spice Kingdom
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Spice Kingdom Owner', NULL, 'spicekingdom@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'spicekingdom@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-SPICEKINGDOM'
FROM users u
WHERE u.email = 'spicekingdom@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'spicekingdom@owner.com')
WHERE name = 'Spice Kingdom';

-- Pizza Orbit
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Pizza Orbit Owner', NULL, 'pizzaorbit@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'pizzaorbit@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-PIZZAORBIT'
FROM users u
WHERE u.email = 'pizzaorbit@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'pizzaorbit@owner.com')
WHERE name = 'Pizza Orbit';

-- Kebab Corner
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Kebab Corner Owner', NULL, 'kebabcorner@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'kebabcorner@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-KEBABCORNER'
FROM users u
WHERE u.email = 'kebabcorner@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'kebabcorner@owner.com')
WHERE name = 'Kebab Corner';

-- Sushi Wave
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Sushi Wave Owner', NULL, 'sushiwave@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'sushiwave@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-SUSHIWAVE'
FROM users u
WHERE u.email = 'sushiwave@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'sushiwave@owner.com')
WHERE name = 'Sushi Wave';

-- Burger Lab
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Burger Lab Owner', NULL, 'burgerlab@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'burgerlab@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-BURGERLAB'
FROM users u
WHERE u.email = 'burgerlab@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'burgerlab@owner.com')
WHERE name = 'Burger Lab';

-- Green Leaf Dhanmondi
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Green Leaf Dhanmondi Owner', NULL, 'greenleafdhanmondi@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'greenleafdhanmondi@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-GREENLEAFDHANMONDI'
FROM users u
WHERE u.email = 'greenleafdhanmondi@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'greenleafdhanmondi@owner.com')
WHERE name = 'Green Leaf Dhanmondi';

-- Shobuj Bhoj
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Shobuj Bhoj Owner', NULL, 'shobujbhoj@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'shobujbhoj@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-SHOBUJBHOJ'
FROM users u
WHERE u.email = 'shobujbhoj@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'shobujbhoj@owner.com')
WHERE name = 'Shobuj Bhoj';

-- Cafe Nova
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Cafe Nova Owner', NULL, 'cafenova@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'cafenova@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-CAFENOVA'
FROM users u
WHERE u.email = 'cafenova@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'cafenova@owner.com')
WHERE name = 'Cafe Nova';

-- Curry Yard
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'Curry Yard Owner', NULL, 'curryyard@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'curryyard@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-CURRYYARD'
FROM users u
WHERE u.email = 'curryyard@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'curryyard@owner.com')
WHERE name = 'Curry Yard';

-- BSMA Restaurant
INSERT INTO users (id, role, name, phone, email, password_hash)
SELECT users_seq.NEXTVAL, 'owner', 'BSMA Restaurant Owner', NULL, 'bsmarestaurant@owner.com',
       '$2a$10$0eZJ5IXwXPXW.EnWKBJfDOyR9t0BUmTus3UzxStK2IFwthgXjP6C2'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'bsmarestaurant@owner.com');

INSERT INTO owners (id, nid)
SELECT u.id, 'NID-BSMARESTAURANT'
FROM users u
WHERE u.email = 'bsmarestaurant@owner.com'
  AND NOT EXISTS (SELECT 1 FROM owners o WHERE o.id = u.id);

UPDATE restaurants
SET owner_id = (SELECT o.id FROM owners o JOIN users u ON u.id = o.id WHERE u.email = 'bsmarestaurant@owner.com')
WHERE name = 'BSMA Restaurant';

COMMIT;
